services:
    chat_app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: chat_app
        restart: unless-stopped
        volumes:
            - .:/var/www
        networks:
            - app_network
        depends_on:
            - chat_postgres

    chat_node:
        image: node:22
        container_name: chat_node
        working_dir: /var/www
        volumes:
            - ./:/var/www
        tty: true
        ports:
            - "5173:5173"  # For Vite development server
        environment:
            - NODE_ENV=development
        command: >
            sh -c "npm install && npm run dev"
        networks:
            - app_network

    chat_web:
        container_name: chat_web
        image: nginx:alpine  # Use the Nginx image
        ports:
            - "9000:80"  # Map port 9000 on the host to port 80 inside the container
        volumes:
            - ./:/var/www  # Mount the Laravel application directory
            - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Use our Nginx config
        depends_on:
            - chat_app  # Ensure PHP-FPM is started before Nginx
        networks:
            - app_network  # Connect to the custom network

    chat_postgres:
        image: postgres
        container_name: chat_postgres
        restart: always
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - app_network
        expose:
            - 5432
        ports:
            - "1243:5432"

    chat_pgadmin:
        image: dpage/pgadmin4
        container_name: chat_pgadmin
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        ports:
            - "9009:80"
        networks:
            - app_network

volumes:
    postgres_data:

networks:
    app_network:
        driver: bridge
